### ISSUE TITLE
What about license ?

### ISSUE THREAD

**Issue by sbouth** [scubajorgen/TomTomWatch#16]
Hey,

First, thanks for your job ! what a great Job,  your code is clean, clear and easy to read ! 
Not really an issue but I'm wondering if you allow to reuse your code on other projects ?

---

Here is the context:

I'm writing a mobile application (android first) to manage my runner 3 watch over bluetooth.

I found I could re-use your code to easily add some features like:
- ttbin to gpx conversion
- gpx to route protobuf tomtom format 

(by the way I had to modify https://github.com/scubajorgen/TomTomWatch/blob/a593a1c3e8b74f9975458fd517d2577177bbd94a/src/main/java/net/studioblueplanet/tomtomwatch/GpxReader.java#L153
with
` │+                           (nNode.getNodeName().equals("trkpt")))`
)

I was wondering myself what license I could use in respect with ttwatch, ttblue and TomTomWatch.
This site might give a quick overview:https://choosealicense.com/

But I can't publish my project without your agreement (for a plugin using your code at least) and hope you can choose a license that clarify this point.

---

Thanks for reading,
BR,

sbouth

**Comment by scubajorgen** [comment]
Thanx for the feedback and info on licensing.
 
First of all I am a firm believer of the slogan 'Software is like sex: it's better when it's free'. Therefor this is my contribution to the community. Use it any way you like, but read the disclaimer (uhm, do I actually have a disclaimer?).
I would appreciate if you buy me a beer if you're going to make scandalous and tremendous amounts of money with your app, using my code
I would appreciate if you publish improvements, like you do above :-)

I am not going to sue you if you don't buy me a beer if you make tremendous amounts of money or you keep your sources closed, since I don't want to waste energy on negativity.

I guess GNU gplv3 would fit this the best, but I do not really care.

**Comment by sbouth** [comment]
OK thanks !
(My plan is to make my code free and open source)

**Comment by scubajorgen** [comment]
Added MIT License

**Comment by scubajorgen** [comment]
Completed
