### ISSUE TITLE
Can't synchronise time

### ISSUE THREAD

**Issue by Chillifish** [scubajorgen/TomTomWatch#41]
I so appreciate this app in keeping my watch alive while I can't afford a new one. Unfortunately, I went away and it has reset itself. When I try and synchronise the time, it just gives me the difference between the time on the computer and the time on the watch, but doesn't actually synchronise the time…

**Comment by scubajorgen** [comment]
Yeah, that has to do with how the watch syncs time.
Basically it syncs the time _based on the GPS signal_.
The only thing you can do from TomTomWatch is sync _the timezone_. IE set the difference with respect to UTC equal to your PC.
Don't expect it to sync the time to the PC time to the second, because that won't be of any use: first time you go outside and start the watch it syncs to the satellite time

**Comment by scubajorgen** [comment]
Solved
