### ISSUE TITLE
MacOS 13.6.4 - USB error 3: Unable to claim interface: Access denied (insufficient permissions)

### ISSUE THREAD

**Issue by elgrandifico1** [scubajorgen/TomTomWatch#61]
Hi,
As I understand it, TomTomWatch can not access the watch because of insufficient permissions.
Does anyone has the same issue on macOS ?

best regards,
Julien

**Comment by tigermick** [comment]
Hi 
I have the same issue on Linux Ubuntu.
I use "sudo" to start the application with root permission.
You can start an application with admin permission on MACOS I think ...

**Comment by scubajorgen** [comment]
Unfortunatelly I cannot support MacOS simply because I do not have Apple (I once bought a MacBook pro but was so disappointed that I sold it 3 days later; but I won't bother you with that ;-) ). 
On Linux you need to have access to the USB (add user to the proper group) and you have to add your device to /etc/udev/rules.d. Add a file here like 50-myusb.rules with next content: 

`SUBSYSTEMS=="usb", ATTRS{idVendor}=="1390", ATTRS{idProduct}=="7475", GROUP="users", MODE="0666"`

Again, this is Linux.

**Comment by elgrandifico1** [comment]
> Unfortunatelly I cannot support MacOS simply because I do not have Apple
Ok, I can understand of course :-)
I've used my son's PC under Windows and I could access to my watch :-)
Thank you very much !

**Comment by axgd-code** [comment]
Hi,

I had the exact same issue on macOS Apple Silicon (M3, macOS 15 Sequoia) and managed to fix it using [GitHub Copilot agent mode ("VibeCode")](https://code.visualstudio.com/docs/copilot/copilot-vscode-features) in VS Code.

Two things were needed:

### 1. Build the missing `darwin-aarch64` native library

The app crashes before even trying USB access because the native library `libusb4java-1.3.0-darwin-aarch64.jar` doesn't exist in the official release. You need to build it from source. The upstream build script fails on Apple Silicon due to missing macOS framework linker flags — I've submitted a fix: [usb4java/libusb4java#18](https://github.com/usb4java/libusb4java/pull/18).

### 2. Run with `sudo`

Even after fixing the native library, on macOS you need to run TomTomWatch with administrator privileges so libusb can detach the IOKit kernel driver:

```bash
sudo java -jar TomTomWatch.jar
```

### Ready-to-build fork

I've prepared a fork with all these fixes already integrated: https://github.com/axgd-code/TomTomWatch

Just build with `mvn package` and run with `sudo java -jar target/TomTomWatch.jar`. Confirmed working on macOS 15 Apple Silicon 🎉
